nhan0504/CS326

README.md, jest.config.js, package-lock.json, package.json, src/index.html, src/models/OutfitEntry.js, src/models/WardrobeItem.js, tests/OutfitEntry.test.js, tests/WardrobeItem.test.js
**Updates:**
- Created **OutfitEntry.js** and **WardrobeItem.js** based on the [data.md](https://github.com/nhan0504/CS326/blob/main/team/m2/data.md) document
- Wrote tests for both data models
- Updated README with run and test instructions
**Looking forward:** We can use these classes as we build our front-ends to make back-end integration easier later.
**Example use:**
To use the data models in app.js:
```
import { WardrobeItem } from "/models/WardrobeItem.js";
const wardrobeItem = new WardrobeItem(
'item1',
'user1',
'image.jpg',
'Blue T-shirt',
20.00,
'M',
'Tops',
'Casual',
['Spring', 'Summer'],
'BrandA'
);
```
Note: These models are likely to change over time.
=> Create outfit entry and wardrobe item data models

src/app.js, src/components/BaseComponent/BaseComponent.js, src/components/HomeViewComponent/HomeViewComponent.js, src/components/LogViewComponent/LogViewComponent.js, src/components/LoginViewComponent/LoginViewComponent.js, src/components/NavBarComponent/NavBarComponent.css, src/components/NavBarComponent/NavBarComponent.js, src/components/StatsViewComponent/StatsViewComponent.js, src/components/SuggestionsViewComponent/SuggestionsViewComponent.js, src/components/WardrobeViewComponent/WardrobeViewComponent.js, src/index.html, src/styles.css
Rearchitected project based on the in-class example. HTML code has been migrated to component JavaScript files and CSS is organized by the component it belongs to.
=> Use components for rendering

src/services/OutfitRepositoryService.js
- Use `Events.NewOutfit` instead of string literal
=> Minor fix for OutfitRepositoryService

front-end/package-lock.json, front-end/package.json, front-end/src/components/StatsViewComponent/StatsViewComponent.css, front-end/src/components/StatsViewComponent/StatsViewComponent.js, front-end/src/index.html
- Create a button to download all the charts so they can share with other
- The button will download an image of all the charts
=> Download button for statistic chart

front-end/src/components/LogViewComponent/LogViewComponent.css, front-end/src/components/LogViewComponent/LogViewComponent.js, front-end/src/models/OutfitEntry.js, front-end/src/testing/TestData.js
created search and filter bar, made changes to model, created outfit test data
=> created search and filter bar for logview page

front-end/src/components/WardrobeAddItemForm/WardrobeAddItemForm.css, front-end/src/components/WardrobeAddItemForm/WardrobeAddItemForm.js, front-end/src/components/WardrobeViewComponent/WardrobeViewComponent.css, front-end/src/components/WardrobeViewComponent/WardrobeViewComponent.js, front-end/src/components/constants.js
=> created the front-end display of the wardrobe add item form

front-end/src/components/WardrobeViewComponent/WardrobeViewComponent.css, front-end/src/components/WardrobeViewComponent/WardrobeViewComponent.js, front-end/src/eventhub/Events.js, front-end/src/models/WardrobeItem.js, front-end/src/services/WardrobeRepositoryService.js
When the favorite button is clicked on an item on the wardrobe page, that item's favorite field is updated
=> Add favorite button functionality

front-end/src/components/LogViewComponent/LogViewComponent.css, front-end/src/components/LogViewComponent/LogViewComponent.js, front-end/src/models/OutfitEntry.js, front-end/src/testing/TestData.js, team/reports/hung-nguyen.md
This is basically logbranch merged with main. Created a new branch for easy modification (Sophia's suggestion :D)
=> merge logbranch with main

team/m2/data.md, team/m3/anisha_prathi/feature_sequence_diagram.md, team/reports/anisha-prathi.md
created a sequence diagram, updated report, and updated data.md
=> Logfeatureseqdiagram

front-end/src/components/WardrobeViewComponent/WardrobeViewComponent.css
Fixes issue where wardrobe items were displayed in a column
=> Fix wardrobe layout bug

front-end/src/components/WardrobeAddItemForm/WardrobeAddItemForm.js, front-end/src/components/WardrobeViewComponent/WardrobeViewComponent.js
-Deleting an item just added no longer deletes everything 
-The deleted item is properly removed from the displayed array so that it will not reappear if you filter
=> Fixed bugs for deleting a wardrobe item:

front-end/src/app.js
**Bug report from @AshleyMcN:** "When I'm logged in, I can still see the please log in message at the bottom of every page"
**Fix:** The login prompts are now deleted every time a new page is navigated to and they are rendered only when a user is not logged in
=> Fix error where login prompt appeared after login

back-end/source/Server.js, back-end/source/controller/WardrobeController.js, back-end/source/model/SQLiteWardrobeModel.js, back-end/source/routes/StatRoutes.js
- Create "/v1/stats" endpoint and `StatRoutes` route 
- Create 5 functions in `WardrobeController` to handle the request and call function in `SQLiteWardrobeModel` to aggreagate data in the database and return it. These are the 5 endpoint
- Top 5 most worn items `http://localhost:4000/stats/most-worn`
- List of items worn less than 2 times: `http://localhost:4000/v1/stats/least-worn`
- Cost per wear for each item: `http://localhost:4000/v1/stats/cost-per-wear`
- Wear frequency of items in each category: `http://localhost:4000/v1/stats/category-frequency`
- Number of items in each category: `http://localhost:4000/v1/stats/items-per-category`
For easiest testing without having a user login, hardcode a `userId` with `req.user = { googleId: "user-123" };`
```Javascript
async …
```
=> Stat data aggregation endpoints

back-end/source/Server.js, back-end/source/controller/WardrobeController.js, back-end/source/routes/SuggestionsRoutes.js
=> Suggestions Page Routes and Endpoints #90: Create a route for the suggestions data so that it can be fetched from the frontend

back-end/source/controller/WardrobeController.js, back-end/source/model/SQLiteWardrobeModel.js
Implemented the function `getSuggestedOutfits(req, res)` in `WardrobeController` to handle requests for suggested outfits. This function calls a function `generateSuggestedOutfits(userId, maxNumSuggestions = 10)` in `SQLiteWardrobeModel` that aggregates suggestions data in the database and returns a list of suggested outfits in the form of an array of arrays of WardrobeItem IDs. This can all be reached using the `http://localhost:4000/v1/suggestions` endpoint created in Issue #90.
To test this, you can follow [Abby's instructions](https://github.com/nhan0504/CS326/pull/99) from her similar PR.
Filtering will be handled in Issue #92 owned by @hungumass. This PR does not connect the front- and back-end.
=> Suggestions page data aggregation #89: Create WardrobeController function that generates suggested outfits

back-end/source/controller/WardrobeController.js, back-end/source/model/InMemoryWardrobeItemModel.js, back-end/source/model/SQLiteWardrobeModel.js, back-end/source/routes/ItemRoutes.js, front-end/src/components/WardrobeViewComponent/WardrobeViewComponent.js, front-end/src/eventhub/Events.js, front-end/src/models/User.js, front-end/src/services/WardrobeRepositoryService.js
Using postman, make a POST to http://localhost:4000/v1/items/ where the user_id of the item is your user id so that your user has items in the database.
Then refresh wardrobe.
=> Fetch wardrobe items #81

back-end/source/controller/OutfitController.js, back-end/source/model/SQLiteOutfitModel.js
- Fixing outfit Item endpoint
- Modifying SQLiteOutfitModel.js for examples and try catch debugging
- Send a POST request at `http://localhost:4000/v1/outfits`
- Example:
```JSON
{
"outfit_id": "2",
"user_id": "user-7749",
"wardrobe_item_ids": ["Blue T-shirt", "Red Pants"],
"note": "First outfit!",
"occasion": "Casual",
"created_at": "2023-12-25",
"updated_at": "2023-12-25"
}
``` 
https://github.com/user-attachments/assets/ed4f9b55-08e5-4e03-a1f2-4bc37b668c94
=> Fixing outfit Item endpoint

team/m2/data.md, team/m2/roles.md, team/reports/abby-tran.md
- Update report and `roles.md`
- Update `data.md` with the data of the statistic
=> Abby update roles.md

back-end/source/controller/OutfitController.js, back-end/source/model/InMemoryOutfitEntryModel.js, back-end/source/model/SQLiteOutfitModel.js, back-end/source/routes/OutfitRoutes.js, front-end/src/components/LogViewComponent/LogViewComponent.js, front-end/src/services/OutfitRepositoryService.js
Using Postman, send a POST request to http://localhost:4000/v1/outfits/ with the user_id set to your user ID in the request body. This will add outfits to the database for your user. Then refresh the log page
=> Fetch Outfits #79

back-end/source/controller/WardrobeController.js, back-end/source/routes/ItemRoutes.js, front-end/package-lock.json, front-end/src/components/WardrobeUpdateItemForm/WardrobeUpdateItemForm.css, front-end/src/components/WardrobeUpdateItemForm/WardrobeUpdateItemForm.js, front-end/src/components/WardrobeViewComponent/WardrobeViewComponent.css, front-end/src/components/WardrobeViewComponent/WardrobeViewComponent.js, front-end/src/services/WardrobeRepositoryService.js
Changes:
- Add update wardrobe item handler in  WardrobeController.js.
- Add route for PUT requests for wardrobe items.
- Add wardrobe item update form component.
- Add wardrobe item update form component to wardrobe view component.
- Add update wardrobe item to wardrobe repository service. 
Reason:
- These changes will allow users to update the information of their wardrobe item in the UI as well as in the database.
=> Update Wardrobe Item #86
